Domain record with digital_ocean_domain is not idempotent and throw error:
digital_ocean_domain is broken (error "'Domain' object has no attribute 'id'") when you run the plabook the second time. Keep the "DNS name" empty to avoid this error.

so need to remove record first and then add it again.

Also CNAME are not supported